# -*- coding: utf-8 -*-
"""Calculadora_exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYYH2nRU77mOk1YxMflZb0ut93fBj8UH
"""

nome = input('Olá, qual o seu nome? ')
print('Seja bem vindo ',nome,'! Este programa mostrará o resultado das principais operações matemáticas de dois numeros.')
resposta = 'sim'
while resposta == 'sim' or resposta == 'Sim':
  num1 = int(input('Digite o primeiro numero: '))
  num2 = int(input('Digite o segundo numero: '))
  soma = num1 + num2
  subtracao = num1 - num2
  multiplicacao = num1 * num2
  divisao = num1 / num2
  print('A soma dos numeros é: ',soma)
  print('A subtração dos numeros é: ',subtracao)
  print('A multiplicação dos numeros é: ',multiplicacao)
  print('A divisão dos numeros é: ',divisao)

  resposta = input('Deseja fazer outra operação com outros números? Digite sim ou não ')
  while resposta != 'sim' and resposta != 'Sim' and resposta != 'não' and resposta !='Não':
    print('Resposta inválida, tente novamente')
    resposta = input('Deseja fazer outra operação? Digite sim ou não ')

print('Até mais!')